### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by Isma3ilMohamed** [DMGDesignUK/DmgLocationUtils#2]
hey @DMGDesignUK 
first of all i want to thank you for this fantastic library
second when i implement in on app that have min sdk = 19
this error happened
Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.github.DMGDesignUK:DmgLocationUtils:v1.0.0] [com.github.DMGDesignUK:DmgLocationUtils:v1.0.0] C:\Users\me\.gradle\caches\transforms-1\files-1.1\DmgLocationUtils-v1.0.0.aar\f4831567f985fe14ca2fe35e39638dba\AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.dmgdesignuk.locationutils" to force usage (may lead to runtime failures)
so i want to use this sdk version to be suitable for lower api devices ...?

**Comment by DMGDesignUK** [comment]
Hi @Isma3ilMohamed,

Thanks for raising this. I think I know what the issue is. Unfortunately I'm away with work for a day or two but I'll look into fixing this as soon as I get back.

In the meantime try using tools:overrideLibrary="com.dmgdesignuk.locationutils" to force usage and then wrapping the permission request logic in an if-else block checking for SDK version > 23. That should do the trick for now (but for obvious reasons I wouldn't recommend using it in a production app). As I said I'll investigate and try to implement a fix as soon as possible.

Thanks.

**Comment by Isma3ilMohamed** [comment]
i did that but error is the same bro

**Comment by DMGDesignUK** [comment]
I've just changed the minSdkVersion for the library. See if it works now and let me know how you get on.
 
Note: until I get chance to update the library to handle for an SDK version lower than 23 you'll still need to wrap the permission request logic in an SDK check to prevent potential run-time crashes. I'll get it updated as soon as possible. **Edit:** or just exclude the run-time permission checking altogether if you're _only_ targeting SDKs lower than 23.

**Comment by DMGDesignUK** [comment]
Should be fixed in latest release but if not please open another issue.
